producer_sim :
    DAQ0 :
        kind : pybar_fei4
        delay : 0.1
        backend: tcp://127.0.0.1:5500
        data_file: 30_mmc32_telescope_5.h5  ## the data file will not be included because of its size 

converter :
    DUT0_Interpreter :
        kind : pybar_mimosa26
        frontend : tcp://127.0.0.1:5500
        backend : tcp://127.0.0.1:5600
    DUT0_Histogrammer :
        kind : pybar_mimosa26_histogrammer
        frontend : tcp://127.0.0.1:5600
        backend : tcp://127.0.0.1:5700

receiver :
    DUT0 :
        kind : pybar_mimosa26
        frontend : tcp://127.0.0.1:5700
