producer_sim :
    DAQ0 :
       kind : pybar_fei4
       delay : 0.1
       backend: tcp://127.0.0.1:5500
       data_file: /home/pascal/git/silab_online_monitor/examples/pyBAR/pybar_data.h5



converter :
    DUT0_Interpreter :
        kind : pybar_fei4
        frontend : tcp://127.0.0.1:5500
        backend : tcp://127.0.0.1:5600
    DUT1_Interpreter :
        kind : pybar_fei4
        frontend : tcp://127.0.0.1:5500
        backend : tcp://127.0.0.1:5601

    DUT0_Correlator :
        kind : hit_correlator
        frontend : [tcp://127.0.0.1:5600, tcp://127.0.0.1:5601]
        backend : tcp://127.0.0.1:5700

receiver :
    DUT0 :
        kind : pybar_fei4
        frontend : tcp://127.0.0.1:5700
